sonar.organization=jwp23
sonar.projectKey=jwp23_throwntom
sonar.sources=.
sonar.exclusions=docs/**
sonar.go.coverage.reportPaths=coverage.out
sonar.swift.coverage.reportPaths=swift-coverage.txt
sonar.qualitygate.wait=true
